# Generated by Django 4.1.4 on 2023-03-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitems',
            name='budget_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetitems',
            name='current_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetitems',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budgetitems',
            name='transactions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitems',
            name='category',
            field=models.CharField(blank=True, choices=[('Food and Drink', 'Food and Drink'), ('Transportation', 'Transportation'), ('Shops', 'Shops'), ('Transfer', 'Transfer'), ('Service', 'Service'), ('Payment', 'Payment'), ('Income', 'Income'), ('Subscription', 'Subscription'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
