# Generated by Django 4.1.4 on 2023-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='users_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
