# Generated by Django 4.1.4 on 2023-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0003_bankaccount_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='users_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
