# Generated by Django 4.1.4 on 2023-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0004_goal_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_transactions', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
