# Generated by Django 4.1.4 on 2023-01-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0005_changedtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
