# Generated by Django 4.1.4 on 2023-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0006_goal_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
