# Generated by Django 4.1.4 on 2023-03-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0006_budgetusers_credit_avaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetusers',
            name='investments',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetusers',
            name='loans',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetusers',
            name='real_estate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
