# Generated by Django 4.1.4 on 2023-01-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0007_goal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, choices=[('Food and Drink', 'Food and Drink'), ('Transportation', 'Transportation'), ('Shops', 'Shops'), ('Transfer', 'Transfer'), ('Service', 'Service'), ('Payment', 'Payment'), ('Income', 'Income')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goalImages/'),
        ),
    ]
