# Generated by Django 4.1.4 on 2023-01-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0008_alter_goal_category_alter_goal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitems',
            name='users_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
