# Generated by Django 4.1.4 on 2023-01-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Budget', '0010_rename_changedtransactions_monthlysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlysummary',
            name='users_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
