# Generated by Django 4.1.4 on 2023-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0011_monthlysummary_user_monthlysummary_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysummary',
            name='all_transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
