# Generated by Django 4.1.4 on 2023-01-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0012_monthlysummary_all_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='account_transactions',
            field=models.CharField(blank=True, max_length=999999999999999999, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='all_transactions',
            field=models.CharField(blank=True, max_length=999999999999999999, null=True),
        ),
    ]
