# Generated by Django 4.1.4 on 2023-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0013_alter_monthlysummary_account_transactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysummary',
            name='account_transactions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysummary',
            name='all_transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
