# Generated by Django 4.1.4 on 2022-12-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
