# Generated by Django 4.1.4 on 2022-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_budget',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='has_university',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
