# Generated by Django 4.1.4 on 2022-12-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_account_has_budget_account_has_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='has_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='has_university',
            field=models.BooleanField(default=False),
        ),
    ]
