# Generated by Django 4.1.4 on 2022-12-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_account_has_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
