# Generated by Django 4.1.4 on 2023-01-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_account_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='changed_transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
