# Generated by Django 4.1.4 on 2022-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_students', models.IntegerField()),
                ('access_token', models.CharField(blank=True, max_length=12, null=True)),
                ('school_email_at', models.CharField(blank=True, max_length=50, null=True)),
                ('school_image', models.ImageField(blank=True, upload_to='schoolImages/')),
            ],
        ),
    ]
