# Generated by Django 4.1.4 on 2022-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
