# Generated by Django 4.1.4 on 2022-12-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='class_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
