# Generated by Django 4.1.4 on 2022-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
