# Generated by Django 4.1.4 on 2023-02-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='creditCardImages/'),
        ),
    ]
