# Generated by Django 4.1.4 on 2022-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_id_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
