# Generated by Django 4.1.4 on 2022-12-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_student_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_progress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
