# Generated by Django 4.1.4 on 2023-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_creditcard_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
