# Generated by Django 4.1.4 on 2022-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_student_age_student_ethnicity_student_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
