# Generated by Django 4.1.4 on 2023-02-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_creditcard_apr'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='atmFee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='credit_card_descrption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='yearlyFee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
