# Generated by Django 4.1.4 on 2022-12-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_majors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Majors',
        ),
    ]
