# Generated by Django 4.1.4 on 2023-02-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_creditcard_atmfee_creditcard_credit_card_descrption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='back_btn_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
