# Generated by Django 4.1.4 on 2023-02-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_anytimedecision_back_btn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='signup_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
