# Generated by Django 4.1.4 on 2022-12-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_student_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
