# Generated by Django 4.1.4 on 2023-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_creditcard_signup_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
