# Generated by Django 4.1.4 on 2023-02-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_job_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.major'),
        ),
    ]
