# Generated by Django 4.1.4 on 2022-12-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0011_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_link',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
