# Generated by Django 4.1.4 on 2022-12-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_video_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='back_button',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='next_button',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
