# Generated by Django 4.1.4 on 2023-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='apy',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_ATM_Fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_Account_Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_Yearly_Fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_feature1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_feature2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_feature3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_feature4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_img',
            field=models.ImageField(blank=True, null=True, upload_to='creditCardImages/'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
