# Generated by Django 4.1.4 on 2022-12-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_video_back_button_video_next_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
