# Generated by Django 4.1.4 on 2023-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_bankaccount_apy_bankaccount_bank_atm_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_monthly_expenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_img',
            field=models.ImageField(blank=True, null=True, upload_to='bankAccountImages/'),
        ),
    ]
