# Generated by Django 4.1.4 on 2023-02-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_student_total_monthly_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_signup_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
