# Generated by Django 4.1.4 on 2022-12-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_job_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/jobimages/'),
        ),
    ]
