# Generated by Django 4.1.4 on 2023-02-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_bankaccount_bank_signup_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vocab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
