# Generated by Django 4.1.4 on 2023-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_video_vocab'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
