# Generated by Django 4.1.4 on 2023-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_video_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
