# Generated by Django 4.1.4 on 2022-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_job_job_type_job_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_401k',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_qualifications',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_requirements',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='dental',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='health',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_hours',
            field=models.CharField(blank=True, choices=[('1', 'Full Time'), ('2', 'Part Time')], max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pay_structure',
            field=models.CharField(blank=True, choices=[('Salary + Bonus', 'Salary + Bonus'), ('Salary + Stock Options', 'Salary + Stock Options'), ('Salary', 'Salary'), ('Hourly Wage + Overtime', 'Hourly Wage + Overtime'), ('Salary + Commission', 'Salary + Commission'), ('Commission Only', 'Commission Only'), ('Fixed Contract', 'Fixed Contract')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pto',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='relocation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='student_loan_assist',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='vision',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('1', 'On-Site'), ('2', 'Hybrid'), ('3', 'Remote')], max_length=400, null=True),
        ),
    ]
