# Generated by Django 4.1.4 on 2023-02-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_anytimedecision_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anytimedecision',
            name='back_btn_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='decision_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='learning_objectives',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='name_id',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='next_btn_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='step2_path',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='summary',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='video_link',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='anytimedecision',
            name='vocab',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
