# Generated by Django 4.1.4 on 2022-12-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_job_company_401k_job_company_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_hours',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=400, null=True),
        ),
    ]
