# Generated by Django 4.1.4 on 2022-12-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_alter_job_job_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('On-Site', 'On-Site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], max_length=400, null=True),
        ),
    ]
