# Generated by Django 4.1.4 on 2023-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0021_budgetitemsuniversity_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='all_transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
