# Generated by Django 4.1.4 on 2022-12-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
