# Generated by Django 4.1.4 on 2023-02-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0022_student_all_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitemsuniversity',
            name='budget_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
