# Generated by Django 4.1.4 on 2023-01-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0023_job_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnytimeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
