# Generated by Django 4.1.4 on 2023-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0023_budgetitemsuniversity_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitemsuniversity',
            name='current_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
