# Generated by Django 4.1.4 on 2023-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0024_anytimedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
