# Generated by Django 4.1.4 on 2023-02-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0024_budgetitemsuniversity_current_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitemsuniversity',
            name='current_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
