# Generated by Django 4.1.4 on 2023-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_anytimedecision_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='decision_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
