# Generated by Django 4.1.4 on 2023-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0025_alter_budgetitemsuniversity_current_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
