# Generated by Django 4.1.4 on 2023-02-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0026_anytimedecision_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
