# Generated by Django 4.1.4 on 2023-01-16 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0026_anytimedecision_decision_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItemsUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Food and Drink', 'Food and Drink'), ('Transportation', 'Transportation'), ('Shops', 'Shops'), ('Transfer', 'Transfer'), ('Service', 'Service'), ('Payment', 'Payment'), ('Income', 'Income')], max_length=200, null=True)),
                ('total_per_month', models.IntegerField(blank=True, null=True)),
                ('users_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
