# Generated by Django 4.1.4 on 2023-02-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0027_student_monthly_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
