# Generated by Django 4.1.4 on 2023-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0028_modulesummarie'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
