# Generated by Django 4.1.4 on 2023-02-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0029_subscription_subscription_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
