# Generated by Django 4.1.4 on 2023-01-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0029_universitymodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesummarie',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.universitymodule'),
        ),
    ]
