# Generated by Django 4.1.4 on 2023-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0030_modulesummarie_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesummarie',
            name='unlocked_decisions',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='modulesummarie',
            name='what_happened',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
