# Generated by Django 4.1.4 on 2023-02-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0030_subscription_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_expense_title', models.CharField(blank=True, max_length=250, null=True)),
                ('monthly_expense_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
