# Generated by Django 4.1.4 on 2023-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0031_modulesummarie_unlocked_decisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesummarie',
            name='points_earned',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='universitymodule',
            name='end_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='universitymodule',
            name='start_date',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
