# Generated by Django 4.1.4 on 2023-02-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0031_monthlyexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenses',
            name='monthly_expense_cost',
            field=models.IntegerField(blank=True, choices=[('$>100', '$>100'), ('$100-$200', '$100-$200'), ('$200-$300', '$200-$300'), ('$300-$400', '$300-$400'), ('$400-$500', '$400-$500')], null=True),
        ),
    ]
