# Generated by Django 4.1.4 on 2023-01-16 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0032_modulesummarie_points_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesummarie',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulesummarie',
            name='users_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
