# Generated by Django 4.1.4 on 2023-02-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0032_alter_monthlyexpenses_monthly_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpenses',
            name='monthly_expense_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
