# Generated by Django 4.1.4 on 2023-01-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0033_modulesummarie_user_modulesummarie_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulesummarie',
            old_name='module_title',
            new_name='module_url',
        ),
    ]
