# Generated by Django 4.1.4 on 2023-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0033_alter_monthlyexpenses_monthly_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitemsuniversity',
            name='category',
            field=models.CharField(blank=True, choices=[('Food and Drink', 'Food and Drink'), ('Transportation', 'Transportation'), ('Shops', 'Shops'), ('Transfer', 'Transfer'), ('Service', 'Service'), ('Payment', 'Payment'), ('Income', 'Income'), ('Subscription', 'Subscription')], max_length=200, null=True),
        ),
    ]
