# Generated by Django 4.1.4 on 2023-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0034_rename_module_title_modulesummarie_module_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='jobs_applied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
