# Generated by Django 4.1.4 on 2023-02-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0034_alter_budgetitemsuniversity_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MonthlyExpenses',
            new_name='MonthlyExpense',
        ),
    ]
