# Generated by Django 4.1.4 on 2023-02-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0035_rename_monthlyexpenses_monthlyexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='monthly_expense_cost',
            field=models.IntegerField(blank=True, choices=[('$0-100', '$0-100'), ('$100-200', '$100-200')], null=True),
        ),
    ]
