# Generated by Django 4.1.4 on 2023-02-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0036_alter_monthlyexpense_monthly_expense_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spending_profile_monthly_payments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
