# Generated by Django 4.1.4 on 2023-02-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0037_student_spending_profile_monthly_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='spender_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
