# Generated by Django 4.1.4 on 2023-01-17 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0037_alter_student_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='discription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
