# Generated by Django 4.1.4 on 2023-01-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0038_anytimedecision_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anytimedecision',
            old_name='discription',
            new_name='description',
        ),
    ]
