# Generated by Django 4.1.4 on 2023-02-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0038_student_spender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.location'),
        ),
    ]
