# Generated by Django 4.1.4 on 2023-01-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0039_rename_discription_anytimedecision_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accepted_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
