# Generated by Django 4.1.4 on 2023-02-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0039_apartment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='monthlyExpenseImages/'),
        ),
    ]
