# Generated by Django 4.1.4 on 2023-02-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0040_monthlyexpense_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
