# Generated by Django 4.1.4 on 2023-01-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0040_student_accepted_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
