# Generated by Django 4.1.4 on 2023-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0041_anytimedecision_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anytimedecision',
            old_name='cost',
            new_name='monthly_cost',
        ),
        migrations.AddField(
            model_name='anytimedecision',
            name='yearly_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
