# Generated by Django 4.1.4 on 2023-02-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0041_alter_subscription_subscription_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptionImages/'),
        ),
    ]
