# Generated by Django 4.1.4 on 2023-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0042_rename_cost_anytimedecision_monthly_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesummarie',
            name='whats_happened',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
