# Generated by Django 4.1.4 on 2023-02-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0042_subscription_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodule',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
