# Generated by Django 4.1.4 on 2023-02-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0043_universitymodule_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_net_worth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
