# Generated by Django 4.1.4 on 2023-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0043_modulesummarie_whats_happened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anytimedecision',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
