# Generated by Django 4.1.4 on 2023-01-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0044_alter_anytimedecision_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='learning_objectives',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='anytimedecision',
            name='vocab',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
