# Generated by Django 4.1.4 on 2023-01-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0046_anytimedecision_next_btn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitemsuniversity',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
