# Generated by Django 4.1.4 on 2023-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0047_budgetitemsuniversity_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
