# Generated by Django 4.1.4 on 2023-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0047_alter_student_graduation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_months_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
