# Generated by Django 4.1.4 on 2023-01-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0048_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anytimedecision',
            name='next_btn_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
