# Generated by Django 4.1.4 on 2023-01-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0049_alter_anytimedecision_next_btn_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='name_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
