# Generated by Django 4.1.4 on 2023-01-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0050_anytimedecision_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anytimedecision',
            name='step2_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
