# Generated by Django 4.1.4 on 2023-02-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0051_student_completedanytimedecisions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='net_income_monthly_list',
            new_name='net_worth_monthly_list',
        ),
    ]
