# Generated by Django 4.1.4 on 2023-01-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0051_anytimedecision_step2_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('sqFeet', models.CharField(blank=True, max_length=500, null=True)),
                ('yearly_cost', models.CharField(blank=True, max_length=500, null=True)),
                ('general_information', models.TextField(blank=True, max_length=500, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=500, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
