# Generated by Django 4.1.4 on 2023-01-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0052_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='yearly_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
