# Generated by Django 4.1.4 on 2023-01-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0053_alter_apartment_yearly_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='apartmentImages/'),
        ),
    ]
