# Generated by Django 4.1.4 on 2023-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0053_student_current_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_month',
            field=models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=200, null=True),
        ),
    ]
