# Generated by Django 4.1.4 on 2023-02-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0054_alter_student_current_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='completedAnytimeDecisions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
