# Generated by Django 4.1.4 on 2023-01-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0055_student_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('f', 'Female'), ('m', 'Male'), ('n', 'Not Specified')], max_length=20, null=True),
        ),
    ]
