# Generated by Django 4.1.4 on 2023-01-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0057_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black or African American'), ('latin', 'Hispanic or Latino'), ('native american', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('islander or hawaiian', 'Native Hawaiian or Other Pacific Islander'), ('other', 'Multiracial/Other')], max_length=20, null=True),
        ),
    ]
