# Generated by Django 4.1.4 on 2023-02-09 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0057_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('sqFeet', models.CharField(blank=True, max_length=500, null=True)),
                ('yearly_cost', models.IntegerField(blank=True, null=True)),
                ('general_information', models.TextField(blank=True, max_length=500, null=True)),
                ('bedrooms', models.CharField(blank=True, max_length=500, null=True)),
                ('bathrooms', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='apartmentImages/')),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.location')),
            ],
        ),
    ]
