# Generated by Django 4.1.4 on 2023-01-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0058_alter_student_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_progress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
