# Generated by Django 4.1.4 on 2023-02-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0058_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='investing_activated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
