# Generated by Django 4.1.4 on 2023-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0059_student_investing_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DTC',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
