# Generated by Django 4.1.4 on 2023-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0060_student_dtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pilot',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
