# Generated by Django 4.1.4 on 2023-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0060_anytimedecision_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='life_path',
            field=models.CharField(blank=True, max_length=900000, null=True),
        ),
    ]
