# Generated by Django 4.1.4 on 2023-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0061_student_life_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='life_path',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
