# Generated by Django 4.1.4 on 2023-02-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0061_student_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='live_with_parents',
            field=models.CharField(blank=True, choices=[('I Live With My Parents', 'I Live With My Parents'), ('I Rent', 'I Rent')], max_length=2000, null=True),
        ),
    ]
