# Generated by Django 4.1.4 on 2023-02-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0062_alter_student_age_alter_student_live_with_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='live_with_parents',
            new_name='living_situation',
        ),
    ]
