# Generated by Django 4.1.4 on 2023-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0063_rename_live_with_parents_student_living_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='living_situation',
            field=models.CharField(blank=True, choices=[('I Live With My Parents', 'I Live With My Parents'), ('I Rent', 'I Rent'), ('I own', 'I own')], max_length=2000, null=True),
        ),
    ]
