# Generated by Django 4.1.4 on 2023-01-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0063_universitymodule_next_life_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodule',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='moduleImages/'),
        ),
    ]
