# Generated by Django 4.1.4 on 2023-01-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0064_universitymodule_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yearly_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
