# Generated by Django 4.1.4 on 2023-02-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0066_modulesummarie_module_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='apartments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.apartment'),
        ),
    ]
