# Generated by Django 4.1.4 on 2023-01-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0067_alter_job_salary_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, choices=[('$>10,000', '$>10,000'), ('$10,001-$25,000', '$10,001-$25,000'), ('$25,001-$40,000', '$25,001-$40,000'), ('$40,001-$55,000', '$40,001-$55,000'), ('$55,001-$70,000', '$55,001-$70,000'), ('$70,001-$85,000', '$70,001-$85,000'), ('$85,001-$100,000', '$85,001-$100,000'), ('$100,001-$120,000', '$100,001-$120,000'), ('$120,001-$140,000', '$120,001-$140,000'), ('$140,001-$160,000', '$140,001-$160,000'), ('$160,000+', '$160,000+')], max_length=400),
        ),
    ]
