# Generated by Django 4.1.4 on 2023-01-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0068_alter_job_salary_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
