# Generated by Django 4.1.4 on 2023-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0068_student_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accounts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
