# Generated by Django 4.1.4 on 2023-01-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0069_video_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='initial_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
