# Generated by Django 4.1.4 on 2023-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0069_student_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary'), ('Not Specified', 'Not Specified')], max_length=20, null=True),
        ),
    ]
