# Generated by Django 4.1.4 on 2023-02-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0070_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Black or African American', 'Black or African American'), ('Hispanic or Latino', 'Hispanic or Latino'), ('American Indian or Alaska Native', 'American Indian or Alaska Native'), ('Asian', 'Asian'), ('Native Hawaiian or Other Pacific Islander', 'Native Hawaiian or Other Pacific Islander'), ('Multiracial/Other', 'Multiracial/Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('Non-Binary', 'Non-Binary'), ('Not Specified', 'Not Specified')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
