# Generated by Django 4.1.4 on 2023-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0070_apartment_initial_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='page_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
