# Generated by Django 4.1.4 on 2023-01-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0072_remove_modulesummarie_whats_happened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodule',
            name='unlocked_decisions',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
