# Generated by Django 4.1.4 on 2023-02-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0072_alter_student_graduation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='monthly_expense_cost',
            field=models.IntegerField(blank=True, choices=[('$0-100', '$0-100'), ('$100-200', '$100-200'), ('$200-300', '$200-300'), ('$300-400', '$300-400')], null=True),
        ),
    ]
