# Generated by Django 4.1.4 on 2023-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0073_alter_monthlyexpense_monthly_expense_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitemsuniversity',
            name='category',
            field=models.CharField(blank=True, choices=[('Food and Drink', 'Food and Drink'), ('Transportation', 'Transportation'), ('Shops', 'Shops'), ('Transfer', 'Transfer'), ('Service', 'Service'), ('Payment', 'Payment'), ('Income', 'Income'), ('Subscription', 'Subscription'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
