# Generated by Django 4.1.4 on 2023-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0073_universitymodule_unlocked_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodule',
            name='module_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
