# Generated by Django 4.1.4 on 2023-03-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0074_alter_budgetitemsuniversity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='monthly_expense_cost',
            field=models.IntegerField(blank=True, choices=[('$0-100', '$0-100'), ('$100-200', '$100-200'), ('$200-300', '$200-300'), ('$300-400', '$300-400'), ('$400-500', '$400-500'), ('$500-750', '$500-750'), ('$750-1000', '$750-1000'), ('$1000-1500', '$1000-1500')], null=True),
        ),
    ]
