# Generated by Django 4.1.4 on 2023-03-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0078_student_avaliable_scenarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='transaction_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
