# Generated by Django 4.1.4 on 2023-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0079_scenario_transaction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_category',
            field=models.CharField(blank=True, choices=[('Food and Drink', 'Food and Drink'), ('Transportation', 'Transportation'), ('Shops', 'Shops'), ('Transfer', 'Transfer'), ('Service', 'Service'), ('Payment', 'Payment'), ('Income', 'Income'), ('Subscription', 'Subscription'), ('Miscellaneous', 'Miscellaneous'), ('Other', 'Other')], max_length=500, null=True),
        ),
    ]
