# Generated by Django 4.1.4 on 2023-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0080_scenario_scenario_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='scenario_display',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
