# Generated by Django 4.1.4 on 2023-03-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0081_student_scenario_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_day',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_month',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
