# Generated by Django 4.1.4 on 2023-03-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0082_student_birth_day_student_birth_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='living_situation',
            field=models.CharField(blank=True, choices=[('I Live With My Parents', 'I Live With My Parents'), ('I Rent', 'I Rent'), ('I Own', 'I Own')], max_length=2000, null=True),
        ),
    ]
