# Generated by Django 4.1.4 on 2023-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0085_alter_student_completedanytimedecisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='desired_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
