# Generated by Django 4.1.4 on 2023-03-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0088_job_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='original',
        ),
    ]
