# Generated by Django 4.1.4 on 2023-03-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0089_remove_job_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='original',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=400, null=True),
        ),
    ]
