# Generated by Django 4.1.4 on 2023-02-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=500, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blogImages/')),
                ('section_1_title', models.CharField(blank=True, max_length=500, null=True)),
                ('section_1_content', models.TextField(blank=True, null=True)),
                ('section_2_title', models.CharField(blank=True, max_length=500, null=True)),
                ('section_2_content', models.TextField(blank=True, null=True)),
                ('section_3_title', models.CharField(blank=True, max_length=500, null=True)),
                ('section_3_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
