# Generated by Django 4.1.4 on 2023-02-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='page_type',
            field=models.CharField(blank=True, choices=[('blog_page_1', 'blog_page_1'), ('blog_page_2', 'blog_page_2')], max_length=500, null=True),
        ),
    ]
