# Generated by Django 4.1.4 on 2023-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0004_alter_blogarticle_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
