# Generated by Django 4.1.4 on 2023-02-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0006_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactModelForm',
        ),
    ]
