# Generated by Django 4.1.4 on 2023-02-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWebsite', '0008_contactmodelform_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tool_id', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
